// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adminPage': string;
  'container': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
