// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'films': string;
  'home': string;
  'review': string;
}
export const cssExports: CssExports;
export default cssExports;
